-- CREATE TABLE IF NOT EXISTS tasks (
--   id BIGINT PRIMARY KEY AUTO_INCREMENT,
--   task VARCHAR(255) NOT NULL,
--   completed TINYINT(1) NOT NULL DEFAULT 0
-- );

CREATE TABLE IF NOT EXISTS tasks (
  id BIGSERIAL PRIMARY KEY,
  task VARCHAR(255) NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE
);

